CREATE TABLE module_info (
     id BIGSERIAL PRIMARY KEY,
     createdAt TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
     updatedAt TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
     moduleName VARCHAR(255) NOT NULL,
     moduleDuration INTEGER NOT NULL,
     examType VARCHAR(255) NOT NULL,
     version INTEGER NOT NULL DEFAULT 1
);